### PR TITLE
Allow raising the state limit for building levensthein automata 

### PR DESCRIPTION
**Pull request by proycon**
Allows raising the limit at run time.

Adds new ``build_with_limit()`` and ``new_with_limit()`` methods, retains full backward compatibility

### CODE REVIEW

**Review by BurntSushi — APPROVED** [review]
LGTM, thanks!

**Comment by BurntSushi** [comment]
Looks like there are some long lines. Once those are fixed, this should be good to go.

**Comment by proycon** [comment]
Right, I pushed some formatting fixes, hopefully the check passes now.

**Comment by BurntSushi** [comment]
@proycon Thanks! And yeah, these new CI restrictions on GitHub Actions are really really grating. I really hope GitHub fixes this shit soon, otherwise I'm switching en masse to some other CI system.

**Comment by BurntSushi** [comment]
@proycon OK, you have a build error now. Please run all tests before pushing and run `cargo fmt`.

**Comment by proycon** [comment]
I'm still fighting with rustfmt... hold on...

**Comment by BurntSushi** [comment]
This PR is on crates.io in `fst 0.4.6`.

**Pull request merged**
