### PR TITLE
[WIP] Generalize types

### PR DESCRIPTION
**Pull request by pthariensflame**
**_NOTE:**_ _This pull request is a work in progress; it should not be merged until this message is removed._

The [article introducing `fst`](http://blog.burntsushi.net/transducers/) describes the conditions under which the theory behind this library holds.  Nonetheless, this library has been restricted to bytes and integers in practice.  This pull request aims to address these limitations by generalizing all types to accept any stream of totally ordered values (instead of just sequences of bytes) and any [_abelian group_](https://ncatlab.org/nlab/show/abelian+group) (instead of just integers).  The new type parameters will all be defaulted in such a way that existing source code should not have to be changed at all.

### CODE REVIEW

**Comment by BurntSushi** [comment]
Looks interesting! I've kind of wondered how well Rust's type system would hold up with a change like this. Have you run into any thorny areas, particularly around the streamers?

I would like to note that we should proceed with caution. This library is already too difficult to use, and adding a type parameter to essentially every type will make it even harder to use.

**Comment by pthariensflame** [comment]
@BurntSushi I can't think of anything at the moment, but I'll let you know when I run into something.  I have to get back into the swing of this project after switching over to my own [heavily abstract](https://github.com/pthariensflame/identity.rs) for a while.  :)

**Comment by bluetech** [comment]
I think this would be nice! It's a bit of a shame that the library is restricted to u8 input and u64 output.

I think separating the work to two PRs would be a good idea. One might be worth it while the other isn't. I personally think generalizing the u8 is more important since it cannot be worked around, and would be restricted by a well-known & common trait. The u64 can be worked around by treating it as an index to a vector (more generally, composing some homomorphism u64 -> MyAbelianGroup). 

I don't like the name "Token" for the type parameter generalizing u8. I would prefer "In", "Input", "Sigma" (after the conventional letter used for the input alphabet) or even "Σ" if you're brave enough (hmm actually, looks like Rust requires an unstable feature to allow non-ascii identifiers - too bad).

**Comment by BurntSushi** [comment]
@bluetech I understand why it might appear tempting to generalize the u8. I would strongly urge anyone interested in doing so to experiment with it. However, I am quite concerned with how much complexity such a generalization will add to not only the public API, but the implementation as well (where I am in particular thinking about reading and writing the raw FST bytes).

**Pull request closed without merging**
