### PR TITLE
Fix transition iterator for nodes with 256 transitions

### PR DESCRIPTION
**Pull request by tapeinosyne**
(Presumably the sole purpose of the cast is to denote an interval.)

### CODE REVIEW

**Comment by BurntSushi** [comment]
Cool! Thank you! Is it possible to write a regression test for this?

**Comment by tapeinosyne** [comment]
Certainly. Would something like the test in the amended commit suffice, or would you prefer something less ad hoc?

**Comment by BurntSushi** [comment]
@tapeinosyne I think that looks OK. Does it fail without your fix? If so, then that's good enough for me.

**Comment by tapeinosyne** [comment]
It would be a sorry test if it didn't!

Without the fix, as expected:
- `assert_eq!(node.transitions().count(), 256)`
> thread 'raw::node::tests::node_max_trans' panicked at 'assertion failed: `(left == right)` (left: `0`, right: `256`)' 
-  `assert_eq!(node.len(), node.transitions().count())`
> thread 'raw::node::tests::node_max_trans' panicked at 'assertion failed: `(left == right)` (left: `256`, right: `0`)'

**Comment by BurntSushi** [comment]
Awesome, thank you!

**Pull request merged**
